version: '3.9'

services:
  arangodb:
    image: arangodb:3.12
    container_name: graph-databases-arangodb
    ports:
      - "8529:8529"  # web interface
    environment:
      ARANGO_ROOT_PASSWORD: password
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps

volumes:
  arangodb_data:
  arangodb_apps:
