"""Protocol defining the data loader interface via structural typing.

This module defines the ``BaseLoader`` protocol, which specifies the contract
that all database-specific data loading implementations must satisfy. Like
:mod:`graphonauts.base.client`, this module uses ``typing.Protocol`` for
structural subtyping rather than nominal inheritance.

The loader abstraction encapsulates the full data ingestion pipeline for TPC-H
benchmark data:

1. Reading pipe-delimited ``.tbl`` files generated by the TPC-H ``dbgen`` tool.
2. Transforming tabular rows into the target database's data model (e.g.,
   nodes and relationships for property graph databases).
3. Batch-inserting the transformed data with appropriate transaction sizing
   to balance throughput and memory consumption.

Concrete implementations (e.g., ``Neo4jLoader``) are responsible for respecting
entity dependency order during loading -- for instance, ``Region`` and ``Nation``
nodes must exist before ``Supplier`` nodes that reference them via relationships.

The ``@runtime_checkable`` decorator enables ``isinstance()`` verification at
runtime, which the CLI layer uses for defensive validation when dynamically
loading database modules via ``importlib``.
"""

from typing import Protocol, runtime_checkable


@runtime_checkable
class BaseLoader(Protocol):
    """Data loader interface for populating a graph database with TPC-H data.

    Implementations must provide both ``aload`` and ``aclear`` as
    asynchronous methods. Additionally, implementations are expected to expose
    an ``entity_times: dict[str, float]`` instance attribute that records
    the wall-clock duration (in seconds) for loading each entity type. This
    attribute is read by the benchmark runner after loading completes to
    produce per-entity timing reports. It is not enforced by the protocol
    signature to keep the interface minimal and avoid constraining how
    implementations initialise their internal state.

    Design note:
        The two-method interface (load and clear) supports the benchmark
        lifecycle where data must be loaded once, benchmarked, and then
        optionally cleared for subsequent runs or database comparisons.
        The ``aclear`` method enables repeatable experiments by restoring
        the database to an empty state.
    """

    async def aload(self) -> None:
        """Load all TPC-H entities into the database in dependency order.

        This method orchestrates the full ingestion of TPC-H Scale Factor 1
        data, comprising approximately 7.5 million nodes and 21 million
        relationships across 8 entity types. Implementations should handle
        chunked reading for large entities (orders, line items) and provide
        progress reporting.

        Raises:
            Any database-specific exceptions related to connection failures,
            constraint violations, or transaction errors.
        """
        ...

    async def aclear(self) -> None:
        """Remove all nodes, relationships, and associated data from the database.

        This operation restores the database to an empty state suitable for
        a fresh data load. Implementations should use the most efficient
        bulk-delete mechanism available in the target database.
        """
        ...
